apiVersion: v1

kind: Secret
data:
  MARIADB_PASSWORD: V2Vsa29tMDEh
  MARIADB_USER: bWFyaw==
  MARIADB_ROOT_PASSWORD: V2Vsa29tMDEh
metadata:
  name: mariadb-info
  namespace: database

---

apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    app: mariadb-deployment
  name: mariadb-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy: { }
  template:
    metadata:
      labels:
        app: mariadb
      namespace: database
    spec:
      containers:
        - image: mariadb:10.6
          name: mariadb
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb-info

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb-deployment-service
  namespace: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      nodePort: 31006
  type: NodePort
  selector:
    app: mariadb

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb-deployment-internal
  namespace: database
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
