apiVersion: v1
data:
  PMA_HOST: "mariadb-deployment-internal"
  PMA_PORT: "3306"
  PMA_ARBITRARY: "1"
kind: ConfigMap
metadata:
  name: phpmyadmin-info

---

apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    app: phpmyadmin-deployment
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy: { }
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: phpmyadmin
          name: phpmyadmin
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin-deployment-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31001
  type: NodePort
  selector:
    app: phpmyadmin
